### ISSUE TITLE
Memory access error when falling down

### ISSUE THREAD

**Issue by HybridDog** [SuperTux/supertux#1058]
**SuperTux version:** supertux2 -128-NOTFOUND (latest)
**System information:** lubuntu 18.04

##### Expected behavior
death

##### Actual behavior
memory access error

##### Steps to reproduce actual behavior
Play that level: https://forum.freegamedev.net/viewtopic.php?f=69&t=11365
Stomp on the snow ball enemy and ice cube, then grab the ice cube
Walk left, press right shortly before the gap so that tux slides
Fall down while still holding the ice cube

##### Additional debugging information
```
Thread 1 "supertux2" received signal SIGSEGV, Segmentation fault.
__GI___libc_free (mem=0x4420400043d00000) at malloc.c:3085
3085	malloc.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt full
#0  __GI___libc_free (mem=0x4420400043d00000) at malloc.c:3085
        ar_ptr = <optimized out>
        p = <optimized out>
        hook = 0x0
#1  0x00005555559c3ef0 in GameSession::~GameSession() ()
No symbol table info available.
#2  0x00005555559c3fc0 in GameSession::~GameSession() ()
No symbol table info available.
#3  0x0000555555aa8be2 in Player::handle_horizontal_input() ()
No symbol table info available.
#4  0x0000555555aaa06d in Player::handle_input() ()
No symbol table info available.
#5  0x0000555555aa7d96 in Player::update(float) ()
No symbol table info available.
#6  0x0000555555b640f4 in GameObjectManager::update(float) ()
No symbol table info available.
#7  0x00005555559d8417 in Sector::update(float) ()
No symbol table info available.
#8  0x0000555555b6db5f in GameSession::update(float, Controller const&) ()
No symbol table info available.
#9  0x00005555559d1fe2 in ScreenManager::update_gamelogic(float) ()
No symbol table info available.
#10 0x00005555559d297a in ScreenManager::run() ()
No symbol table info available.
#11 0x00005555559be298 in Main::launch_game(CommandLineArguments const&) ()
No symbol table info available.
#12 0x00005555559bea83 in Main::run(int, char**) ()
No symbol table info available.
#13 0x00005555559bc784 in main ()
No symbol table info available.
```

##### Guidelines for reporting issues

- [ ] I have read <https://github.com/SuperTux/supertux/blob/master/CONTRIBUTING.md#bug-reports>.
- [x] I verified this isn't an issue that's already been reported.
- [x] This report only includes details about **one** (1) issue, feature request or topic.
- [x] If I make a mistake while submitting this report I will use the edit feature instead of closing this issue and opening a new one.
- [x] This issue is **not** about wrong translations (use Transifex for those), or anything unsupported (e.g. third-party add-ons).
- [ ] Once you're done, please remove the section 'Guidelines for reporting issues', the 'Additional debugging information' if it is empty, and any text in *italic font*.

**Comment by HybridDog** [comment]
I've added a backtrace with debugging symbols.

**Comment by Ordoviz** [comment]
Really weird. Sometimes it works, sometimes it doesn’t.

**Comment by MasterOfTheTiger** [comment]
This also happens when the user touches the edge of the world (like at the beginning).
